SELECT ID,
CASE
WHEN GRADE = 1
THEN 'CRITICAL'
WHEN GRADE = 2
THEN 'HIGH'
WHEN GRADE = 3
THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GRADE FROM ECOLI_DATA) AS GRADE_DATA
ORDER BY ID;