SELECT e.ID, e.GENOTYPE, m.PARENT_GENOTYPE
FROM ECOLI_DATA e
LEFT JOIN
(SELECT ID, GENOTYPE AS PARENT_GENOTYPE
 FROM ECOLI_DATA
) m
ON e.PARENT_ID = m.ID
WHERE e.GENOTYPE & m.PARENT_GENOTYPE = m.PARENT_GENOTYPE
ORDER BY ID;